#! /usr/bin/env python
import sys
import time
import codecs
import argparse
import feedparser

sys.stdout = codecs.getwriter('utf-8')(sys.stdout,errors='ignore')

if __name__ == "__main__":
	# parse options
	parser = argparse.ArgumentParser(description='Prints RSS Items to standard output')

	parser.add_argument('--feed', action="append",dest="feeds")
	args = parser.parse_args()

	if args.feeds == None:
		print "No Feeds specified. Aborting."
		sys.exit(1)

	# initialize last feed dictionary
	last_feed = dict()
	for rss in args.feeds:
		last_feed[rss] = list()

	while True:
		for rss in args.feeds:
			feed = feedparser.parse(rss)

			for item in feed["items"]:
				if item not in last_feed[rss]:
					print item["title"] + " " + item["link"]
				# only print one item if we just started
				if not last_feed[rss]:
					break
			sys.stdout.flush()
			last_feed[rss] = feed["items"]
		time.sleep(180)
