#! /usr/bin/env python
import sys
import time
import codecs
import argparse
import feedparser

sys.stdout = codecs.getwriter('utf-8')(sys.stdout,errors='ignore')

if __name__ == "__main__":
	# parse options
	parser = argparse.ArgumentParser(description='Prints RSS Items to standard output')

	parser.add_argument('--feed', action="append",dest="feeds")
	args = parser.parse_args()

	if args.feeds == None:
		print "No Feeds specified. Aborting."
		sys.exit(1)

	# initialize last update dictionary
	last_update = dict()
	for rss in args.feeds:
		last_update[rss] = time.gmtime()

	while True:
		for rss in args.feeds:
			feed = feedparser.parse(rss)

			for item in feed["items"]:
				if item["published_parsed"] > last_update[rss]:
					print item["title"] + "... " + item["link"]
					sys.stdout.flush()
			last_update[rss] = feed["updated_parsed"]
		time.sleep(180)
